apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: gateway-pool
spec:
  blocks:
    - cidr: "192.168.0.219/32"
  serviceSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: default-gateway
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: gateway-l2
spec:
  loadBalancerIPs: true
  externalIPs: false
  interfaces:
    - "^(eth|ens|enp).*"
  serviceSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: default-gateway
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
      - key: feature.node.kubernetes.io/pci-10de.present
        operator: NotIn
        values: ["true"]
