apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-root
  namespace: mysql
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: mysql-root
    creationPolicy: Owner
    template:
      data:
        mysql-root-password: "{{ .password }}"
        mysql-replication-password: "{{ .replicationPassword }}"
  data:
    - secretKey: password
      remoteRef:
        key: mysql/root
        property: password
    - secretKey: replicationPassword
      remoteRef:
        key: mysql/root
        property: replication-password
