apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trino-credentials
  namespace: trino
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: trino-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        password.db: |
          {{ htpasswd .username .password "bcrypt" }}
  data:
    - secretKey: username
      remoteRef:
        key: trino/credentials
        property: username
    - secretKey: password
      remoteRef:
        key: trino/credentials
        property: password
