apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: superset-db-credentials
  namespace: superset
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: superset-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: postgres-cnpg/superset
        property: username
    - secretKey: password
      remoteRef:
        key: postgres-cnpg/superset
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: superset-secret
  namespace: superset
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: superset-secret
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: superset/secret
        property: secret-key
