apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-root
  namespace: mysql
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: mysql-root
    creationPolicy: Owner
    template:
      data:
        rootUser: root
        rootHost: "%"
        rootPassword: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: mysql/root
        property: password
