apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-db-credentials
  namespace: airflow
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: airflow-db-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        connection: "postgresql://{{ .username }}:{{ .password }}@postgres-cluster-rw.postgres-cluster.svc:5432/airflow"
  data:
    - secretKey: username
      remoteRef:
        key: postgres-cnpg/airflow
        property: username
    - secretKey: password
      remoteRef:
        key: postgres-cnpg/airflow
        property: password
