apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-api-secret-key
  namespace: airflow
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: airflow-api-secret-key
    creationPolicy: Owner
  data:
    - secretKey: api-secret-key
      remoteRef:
        key: airflow/api-secret
        property: api-secret-key
