apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-webserver-secret
  namespace: airflow
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: airflow-webserver-secret
    creationPolicy: Owner
  data:
    - secretKey: webserver-secret-key
      remoteRef:
        key: airflow/webserver-secret
        property: webserver-secret-key
