apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-jwt-secret
  namespace: airflow
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: airflow-jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: airflow/jwt-secret
        property: jwt-secret
