apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-admin
  namespace: airflow
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: airflow-admin
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: airflow/admin
        property: password
