apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-default
  namespace: redis
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: redis-default
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: redis/default
        property: password
