apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-slack
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: grafana-slack
    creationPolicy: Owner
  data:
    - secretKey: webhook-url
      remoteRef:
        key: slack/grafana
        property: webhook-url
