apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: openwebui-data
  namespace: openwebui
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  bucketName: openwebui-data
  storageClassName: rook-ceph-bucket
