apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-secret-key
  namespace: openwebui
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: openwebui-secret-key
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: openwebui/secret-key
        property: secret-key
