apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openwebui-admin
  namespace: openwebui
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: openwebui-admin
    creationPolicy: Owner
    template:
      data:
        WEBUI_SECRET_KEY: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: openwebui/admin
        property: password
