apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jupyterhub-db
  namespace: jupyter
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: jupyterhub-db
    creationPolicy: Owner
    template:
      data:
        hub.db.password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: postgres-cnpg/jupyterhub
        property: password
