apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jupyterhub-proxy-auth
  namespace: jupyter
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: hub
    creationPolicy: Merge
    template:
      data:
        hub.config.ConfigurableHTTPProxy.auth_token: "{{ .authToken }}"
        hub.config.JupyterHub.cookie_secret: "{{ .cookieSecret }}"
        hub.config.CryptKeeper.keys: "{{ .cryptkeeperKeys }}"
  data:
    - secretKey: authToken
      remoteRef:
        key: jupyter/proxy-auth
        property: auth-token
    - secretKey: cookieSecret
      remoteRef:
        key: jupyter/proxy-auth
        property: cookie-secret
    - secretKey: cryptkeeperKeys
      remoteRef:
        key: jupyter/proxy-auth
        property: cryptkeeper-keys
