apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hive-db-credentials
  namespace: hive
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: hive-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: postgres-cnpg/hive
        property: username
    - secretKey: password
      remoteRef:
        key: postgres-cnpg/hive
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hive-metastore
  namespace: hive
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: hive-metastore
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: hive/metastore
        property: username
    - secretKey: password
      remoteRef:
        key: hive/metastore
        property: password
