apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-superuser
  namespace: hive
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: postgres-superuser
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: postgres-cnpg/superuser
        property: password
