apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickhouse-credentials
  namespace: clickhouse
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: clickhouse-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: clickhouse/credentials
        property: username
    - secretKey: password
      remoteRef:
        key: clickhouse/credentials
        property: password
