apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: clickhouse
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/component: clickhouse
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  selector:
    app: clickhouse-clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      protocol: TCP
    - name: tcp
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: prometheus
      port: 9363
      targetPort: 9363
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: clickhouse
  namespace: clickhouse
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  parentRefs:
    - name: default-gateway
      namespace: gateway-system
  hostnames:
    - "clickhouse.homelab.xiehang.com"
  rules:
    - backendRefs:
        - name: clickhouse
          port: 8123
