apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudbeaver-admin
  namespace: dbeaver
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: cloudbeaver-admin
    creationPolicy: Owner
    template:
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: dbeaver/admin
        property: username
    - secretKey: password
      remoteRef:
        key: dbeaver/admin
        property: password
