apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cassandra-admin
  namespace: cassandra
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: cassandra-admin
    creationPolicy: Owner
    template:
      data:
        cassandra-password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: cassandra/admin
        property: password
