apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "400"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.5.15
      helm:
        valueFiles:
          - $values/gitops/platform/grafana/values.yaml
    - repoURL: https://github.com/hangxie/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/hangxie/homelab.git
      targetRevision: main
      path: gitops/platform/grafana/extras
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
