apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: mimir-distributed
      targetRevision: 6.0.6
      helm:
        valueFiles:
          - $values/gitops/platform/mimir/values.yaml
    - repoURL: https://github.com/hangxie/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/hangxie/homelab.git
      targetRevision: main
      path: gitops/platform/mimir/extras
  destination:
    server: https://kubernetes.default.svc
    namespace: mimir
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
