apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackable-commons-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "500"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - repoURL: oci.stackable.tech/sdp-charts
      chart: commons-operator
      targetRevision: 26.3.0
      helm:
        valueFiles:
          - $values/gitops/platform/stackable-commons-operator/values.yaml
    - repoURL: https://github.com/hangxie/homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: stackable-commons-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
