architecture: replication

image:
  repository: bitnamilegacy/redis

auth:
  existingSecret: redis-default
  existingSecretPasswordKey: password

global:
  storageClass: rook-ceph-block
  security:
    allowInsecureImages: true

master:
  persistence:
    enabled: true
    size: 8Gi

replica:
  replicaCount: 2
  persistence:
    enabled: true
    size: 8Gi

metrics:
  enabled: true
  image:
    repository: bitnamilegacy/redis-exporter
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-stack
