airflowVersion: "2.10.3"
defaultAirflowTag: "2.10.3"

executor: KubernetesExecutor

createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
  ttlSecondsAfterFinished: null

migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false
  ttlSecondsAfterFinished: null

webserverSecretKeySecretName: airflow-webserver-secret

data:
  metadataConnection:
    user: airflow
    pass: ""        # supplied via metadataSecretName
    protocol: postgresql
    host: postgres-cluster-rw.postgres-cluster.svc
    port: 5432
    db: airflow
    sslmode: disable
  metadataSecretName: airflow-db-credentials

postgresql:
  enabled: false

redis:
  enabled: true
  persistence:
    enabled: true
    storageClassName: rook-ceph-block

dags:
  persistence:
    enabled: true
    storageClassName: rook-cephfs
    size: 5Gi
    accessMode: ReadWriteMany

logs:
  persistence:
    enabled: true
    storageClassName: rook-cephfs
    size: 5Gi

webserver:
  defaultUser:
    enabled: true
    username: admin
    email: admin@homelab.xiehang.com
  startupProbe:
    periodSeconds: 10
    timeoutSeconds: 20
    failureThreshold: 30

statsd:
  enabled: false

flower:
  enabled: false

serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus-stack
