replicaCount: 3

image:
  repository: bitnamilegacy/cassandra

dbUser:
  user: cassandra
  existingSecret: cassandra-admin

global:
  storageClass: rook-ceph-block

persistence:
  enabled: true
  size: 10Gi

metrics:
  enabled: true
  image:
    repository: bitnamilegacy/cassandra-exporter
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-stack
