{
 "title": "OS Metrics",
 "tags": [ "2026.1" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(node_filesystem_avail_bytes, cluster)"
   },
   {
    "name": "dc",
    "label": "dc",
    "query": "label_values(node_filesystem_avail_bytes{cluster=~\"$cluster\"}, dc)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(node_filesystem_avail_bytes{cluster=\"$cluster\", dc=~\"$dc\", job=~\"node_exporter.*\"}, instance)"
   },
   {
    "name": "by",
    "label": "by",
    "query": "Instance : instance,Cluster : cluster,DC : dc,Shard : instance\\,cpu"
   },
   {
    "name": "monitor_disk",
    "query": "node_disk_read_bytes_total{job=~\"node_exporter.*\"}"
   },
   {
    "name": "monitor_network_interface",
    "query": "node_network_receive_packets_total"
   },
   { "name": "mount_point", "label": "Mount path", "query": "node_filesystem_avail_bytes" },
   {
    "name": "cluster_name",
    "label": "cluster_name",
    "query": {
     "query": "label_values(scylla_scylladb_current_version,cluster_name)"
    }
   },
   {
    "name": "account_name",
    "label": "account_name",
    "query": {
     "query": "label_values(scylla_scylladb_current_version,account_name)"
    }
   },
   { "name": "scylla_version", "query": "2026.1" },
   { "name": "monitoring_version", "query": "4.15.0" }
  ]
 },
 "panels": [
  {
   "title": "Cluster OS Information $cluster $account_name $cluster_name ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total Storage $node",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{mountpoint=~\"$mount_point\", instance=~\"$node\", job=~\"node_exporter.*\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{mountpoint=~\"$mount_point\", instance=~\"$node\", job=~\"node_exporter.*\"})-sum(node_filesystem_avail_bytes{mountpoint=~\"$mount_point\", instance=~\"$node\", job=~\"node_exporter.*\"}))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Disk And Partition Information",
   "type": "table",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "label_join(label_replace(node_filesystem_avail_bytes{mountpoint=~\"$mount_point\", instance=~\"$node\", device=~\".*$monitor_disk\", job=~\"node_exporter.*\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\") * on(instance, device) group_left(model) node_disk_info , \"instance_device\", \":\", \"instance\", \"mountpoint\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "1- (label_join(label_replace(node_filesystem_avail_bytes{mountpoint=~\"$mount_point\", instance=~\"$node\", device=~\".*$monitor_disk\", job=~\"node_exporter.*\"}/node_filesystem_size_bytes{mountpoint=~\"$mount_point\", instance=~\"$node\", device=~\".*$monitor_disk\", job=~\"node_exporter.*\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance_device\", \":\", \"instance\", \"mountpoint\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(label_join(label_replace(node_filesystem_size_bytes{mountpoint=~\"$mount_point\", instance=~\"$node\", device=~\".*$monitor_disk\", job=~\"node_exporter.*\"}-node_filesystem_avail_bytes{mountpoint=~\"$mount_point\", instance=~\"$node\", device=~\".*$monitor_disk\", job=~\"node_exporter.*\"}, \"device\", \"$1\", \"device\", \"/dev/(.*)\"), \"instance_device\", \":\", \"instance\", \"mountpoint\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Low-Space Partitions",
   "type": "table",
   "description": "Partitions with low free space",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk(20, node_filesystem_avail_bytes{job=~\"node_exporter.*\", mountpoint=~\"$mount_point\", instance=~\"$node\"}/node_filesystem_size_bytes{job=~\"node_exporter.*\", mountpoint=~\"$mount_point\", instance=~\"$node\"}<0.11)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Partition $mount_point", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "mount_point" },
  {
   "title": "Used disk by $by",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-sum(node_filesystem_avail_bytes{mountpoint=\"$mount_point\", instance=~\"$node\", job=~\"node_exporter.*\"}) by ([[by]])/sum(node_filesystem_size_bytes{mountpoint=\"$mount_point\", instance=~\"$node\", job=~\"node_exporter.*\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Used Bytes by $by",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=\"$mount_point\", instance=~\"$node\", job=~\"node_exporter.*\"}) by ([[by]])-sum(node_filesystem_avail_bytes{mountpoint=\"$mount_point\", instance=~\"$node\", job=~\"node_exporter.*\"}) by ([[by]])"
    },
    {
     "expr": "sum(node_filesystem_size{mountpoint=\"$mount_point\", instance=~\"$node\", job=~\"node_exporter.*\"}) by ([[by]])-sum(node_filesystem_avail{mountpoint=\"$mount_point\", instance=~\"$node\", job=~\"node_exporter.*\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Free Bytes by $by",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{mountpoint=\"$mount_point\", instance=~\"$node\", job=~\"node_exporter.*\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Number of files by $by",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_files{mountpoint=\"$mount_point\", instance=~\"$node\", job=~\"node_exporter.*\"}- node_filesystem_files_free{mountpoint=\"$mount_point\", instance=~\"$node\", job=~\"node_exporter.*\"}) by ([[by]])"
    }
   ]
  },
  { "title": "Disk $monitor_disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "monitor_disk" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 },
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Disk $monitor_disk</h1>"
  },
  {
   "title": "Disk Writes per $by",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_writes_completed_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_disk\", job=~\"node_exporter.*\"}[4m])) by ([[by]])"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_disk\", job=~\"node_exporter.*\"}[4m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Disk Reads per $by",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_disk\", job=~\"node_exporter.*\"}[4m])) by ([[by]])"
    },
    {
     "expr": "sum(rate(node_disk_reads_completed{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_disk\", job=~\"node_exporter.*\"}[4m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Disk Writes Bps per $by",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_disk\", job=~\"node_exporter.*\"}[4m])) by ([[by]])"
    },
    {
     "expr": "sum(rate(node_disk_bytes_written{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_disk\", job=~\"node_exporter.*\"}[4m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Disk Read Bps per $by",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_disk\", job=~\"node_exporter.*\"}[4m])) by ([[by]])"
    },
    {
     "expr": "sum(rate(node_disk_bytes_read{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_disk\", job=~\"node_exporter.*\"}[4m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Read AWait per instance",
   "type": "timeseries",
   "description": "The average read time from disk",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_disk\", job=~\"node_exporter.*\"}[4m])/rate(node_disk_reads_completed_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_disk\", job=~\"node_exporter.*\"}[4m])",
     "legendFormat": "{{dc}} {{instance}}"
    }
   ]
  },
  {
   "title": "Write AWait per instance",
   "type": "timeseries",
   "description": "The average write time to disk",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_disk\", job=~\"node_exporter.*\"}[4m])/rate(node_disk_writes_completed_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_disk\", job=~\"node_exporter.*\"}[4m])",
     "legendFormat": "{{dc}} {{instance}}"
    }
   ]
  },
  {
   "title": "Network Interface $monitor_network_interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "repeat": "monitor_network_interface"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 },
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Network $monitor_network_interface</h1>"
  },
  {
   "title": "Interface Rx Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_network_interface\", job=~\"node_exporter.*\"}[4m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Interface Tx Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_packets_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_network_interface\", job=~\"node_exporter.*\"}[4m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Interface Rx bps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum(8*rate(node_network_receive_bytes_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_network_interface\", job=~\"node_exporter.*\"}[4m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Interface Tx bps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum(8*rate(node_network_transmit_bytes_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_network_interface\", job=~\"node_exporter.*\"}[4m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Interface Received Dropped Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_network_interface\", job=~\"node_exporter.*\"}[4m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Interface Transmit Dropped Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_drop_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", device=\"$monitor_network_interface\", job=~\"node_exporter.*\"}[4m])) by ([[by]])"
    }
   ]
  },
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 63 },
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">CPU and Memory</h1>"
  },
  {
   "title": "Available memory",
   "type": "timeseries",
   "description": "The available memory, note that in a production environment we expect this to be low, Scylla would use most of the available memory when possible",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", job=~\"node_exporter.*\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "Percent of Available memory",
   "type": "timeseries",
   "description": "Percent of available memory, note that in a production environment we expect this to be low, Scylla would use most of the available memory when possible",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", job=~\"node_exporter.*\"}) by ([[by]])/sum(node_memory_MemTotal_bytes{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", job=~\"node_exporter.*\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "CPU used",
   "type": "timeseries",
   "description": "Percent of CPU used, note that in production Scylla would try to use most of the CPU and this is not a problem",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-sum(rate(node_cpu_seconds_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", mode=\"idle\", job=~\"node_exporter.*\"}[3m])) by ([[by]])/count(node_cpu_seconds_total{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", mode=\"idle\", job=~\"node_exporter.*\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "timeseries",
   "description": "CPU frequency should be set for performance.\n\n The current frequency should match the max frequency. If that is not the case, check your host configuration.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "max(node_cpu_scaling_frequency_max_hertz{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", job=~\"node_exporter.*\"}) or on() max(node_cpu_frequency_max_hertz{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", job=~\"node_exporter.*\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "min(node_cpu_scaling_frequency_hertz{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", job=~\"node_exporter.*\"}) by ([[by]]) or on() min(node_cpu_frequency_hertz{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\", job=~\"node_exporter.*\"}) by ([[by]])"
    }
   ]
  },
  {
   "title": "TCP Retransmit",
   "type": "timeseries",
   "description": "reports the number of TCP segments that have been retransmitted, indicating potential network issues or packet loss.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(node_netstat_Tcp_RetransSegs{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\"}[3m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "ethtool limitations - only applicable if ethtool is enabled on nodetool_exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bandwidth-Out allowance exceeded",
     "type": "timeseries",
     "description": "Outbound bandwidth allowance exceed events per second — the rate at which the NIC attempts to transmit above its allowed egress bandwidth limit (often indicating throttling/shaping).",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(node_ethtool_bw_out_allowance_exceeded{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\"}[3m])) by ([[by]])"
      }
     ]
    },
    {
     "title": "Bandwidth-In allowance exceeded",
     "type": "timeseries",
     "description": "Inbound bandwidth allowance exceed events per second — the rate at which the NIC receives above its allowed ingress bandwidth limit (often indicating ingress shaping/throttling).",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(node_ethtool_bw_in_allowance_exceeded{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\"}[3m])) by ([[by]])"
      }
     ]
    },
    {
     "title": "Conntrack allowance exceed",
     "type": "timeseries",
     "description": "Conntrack allowance exceed events per second — the rate at which the system/NIC exceeds its allowed connection-tracking (conntrack) limit, often indicating connection pressure and potential drops or throttling.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(node_ethtool_conntrack_allowance_exceeded{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\"}[3m])) by ([[by]])"
      }
     ]
    },
    {
     "title": "Link-local allowance exceed",
     "type": "timeseries",
     "description": "Link-local allowance exceed events per second — the rate at which the NIC exceeds its allowed link-local traffic limit (e.g., ARP/ND or other local control traffic), often indicating local-network chatter and possible throttling",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(node_ethtool_linklocal_allowance_exceeded{instance=~\"[[node]]\",cluster=\"$cluster\", dc=~\"$dc\"}[3m])) by ([[by]])"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 84 },
     "options": {
      "content": "<div style=\"color:#5780C1; border-bottom: 0px solid #5780C1;\">Scylla Monitoring version - 4.15.0</div> <div style=\"\"><a href=\"https://github.com/scylladb/scylla-monitoring/issues/new?body=scylla-version%3D[[scylla_version]]%0Amonitoring-version%3D[[monitoring_version]]%0Adashboard%3D${__dashboard.uid}\" target=\"_blank\">\n<input title=\"Report an issue with Scylla Monitoring\" type=\"button\" style=\"background-color:#306EE6;color:white;border-radius: 15px;font-size:14px;line-height:22px;padding:2px\" value=\"&nbsp;Report an issue on this page&nbsp;\"></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"/render/d/${__dashboard.uid}?orgId=1&from=${__from}&to=${__to}&width=1600&height=-1&kiosk\" target=\"_blank\" download=\"dashboard_${__dashboard.uid}-${__from:date:iso}.png\"><input title=\"Make a Screenshot\" type=\"button\" style=\"background-color:#306EE6;color:white;border-radius: 15px;font-size:14px;line-height:22px;padding:2px\" value=\"&nbsp;&nbsp;&nbsp;Screenshot&nbsp;&nbsp;&nbsp;\"></input></a></span></div>"
     }
    }
   ]
  }
 ]
}